In [1]:
import os
print(os.getcwd())
os.chdir("../")
print(os.getcwd())

f:\studium\Thesis_Repo\phase1_tgt_model
f:\studium\Thesis_Repo

In [3]:
import pandas as pd
# ---------------------------------------------------------
# STEP 1: Load Real Data from Parquet
# ---------------------------------------------------------
print("Loading data...")

# Adjust these filenames if yours are different
bus_df = pd.read_parquet('data_out/no_pertubations/case14_ieee/raw/bus_data.parquet')
branch_df = pd.read_parquet('data_out/no_pertubations/case14_ieee/raw/branch_data.parquet')

Loading data...

In [5]:
bus_df["Pd"].sum()

np.float64(1394549.0451252912)

In [4]:
bus_df.head()

,scenario,load_scenario_idx,bus,Pd,Qd,Pg,Qg,Vm,Va,PQ,PV,REF,vn_kv,min_vm_pu,max_vm_pu,GS,BS,Va_dc,Pg_dc,scenario_partition
0,0,0.0,0,0.000000,0.000000,1.451907e+02,4.525935,1.056605,0.000000,0.0,0.0,1.0,1.0,0.94,1.06,0.0,0.0,0.000000,1.403542e+02,0
1,0,0.0,1,5.175953,3.029244,-8.597099e-07,3.368291,1.037865,-3.099404,0.0,1.0,0.0,1.0,0.94,1.06,0.0,0.0,-3.641806,-8.597099e-07,0
2,0,0.0,2,60.060690,12.114152,0.000000e+00,11.269902,1.013892,-7.678003,0.0,1.0,0.0,1.0,0.94,1.06,0.0,0.0,-8.790689,0.000000e+00,0
3,0,0.0,3,29.827097,-2.433592,0.000000e+00,0.000000,1.021649,-5.926315,1.0,0.0,0.0,1.0,0.94,1.06,0.0,0.0,-6.859077,0.000000e+00,0
4,0,0.0,4,5.321067,1.120225,0.000000e+00,0.000000,1.022829,-5.002309,1.0,0.0,0.0,1.0,0.94,1.06,0.0,0.0,-5.863499,0.000000e+00,0

In [8]:
loads_pivot = bus_df.pivot(index='load_scenario_idx', columns='bus', values='Pd').fillna(0)
#loads_pivot = loads_pivot[nodes] # Ensure sorted column order
loads_pivot

bus,0,1,2,3,4,5,6,7,8,9,10,11,12,13
load_scenario_idx,,,,,,,,,,,,,,
0.0,0.0,16.992270,73.939988,37.999109,5.588100,8.356411,0.0,0.0,22.030153,7.195522,2.780548,4.890640,10.193243,11.939269
1.0,0.0,15.682611,70.235535,34.793700,5.999752,8.826955,0.0,0.0,22.776800,7.046983,2.732882,4.625811,10.282018,11.761397
2.0,0.0,16.244688,70.224208,35.523459,5.448957,8.645308,0.0,0.0,22.686581,6.595910,2.735090,4.813238,10.510495,11.628571
3.0,0.0,15.732537,69.029690,36.067264,5.593203,8.060470,0.0,0.0,21.575147,6.625683,2.624713,4.725992,10.149131,11.471458
4.0,0.0,15.523636,66.908987,37.432573,5.594928,8.019955,0.0,0.0,22.723371,6.917080,2.571260,4.709379,9.592350,10.980705
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755.0,0.0,17.924999,79.144335,40.233852,6.007503,8.678230,0.0,0.0,23.917659,7.445715,2.729062,4.899720,11.220401,12.582228
8756.0,0.0,17.253666,73.932302,38.630806,5.766287,8.595411,0.0,0.0,23.645373,6.852823,2.740957,5.001866,10.505484,11.471329
8757.0,0.0,17.745984,74.680313,38.929341,6.243964,8.424283,0.0,0.0,22.708236,7.122764,2.876493,4.878686,10.583923,12.245410
8758.0,0.0,16.180295,73.066593,36.176917,6.009285,9.100234,0.0,0.0,23.539017,6.720992,2.663503,4.565141,10.275688,11.301832
8759.0,0.0,16.836459,70.057454,35.732453,5.952016,8.257080,0.0,0.0,21.973814,6.842486,2.580351,4.500920,10.626075,11.414390

In [9]:
flows_pivot = branch_df.pivot(index='load_scenario_idx', columns='idx', values='pf').fillna(0)
flows_pivot

idx,0.0,1.0,2.0,3.0,4.0,5.0,6.0,7.0,8.0,9.0,10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,18.0,19.0
load_scenario_idx,,,,,,,,,,,,,,,,,,,,
0.0,147.913069,63.451447,56.124920,41.522680,29.498448,-19.193901,-50.618754,21.408870,12.350673,33.960306,5.796860,6.095037,13.711999,0.0,21.408870,4.228894,7.500496,-2.975613,1.159853,4.547588
1.0,142.103142,61.432964,53.679248,40.302214,28.955088,-17.815857,-47.845409,21.837701,12.602900,33.936341,5.627086,5.916034,13.566267,0.0,21.837701,4.198740,7.465061,-2.857322,1.248183,4.403954
2.0,142.437961,61.397479,53.647647,40.247086,28.798134,-17.834757,-48.257676,21.590839,12.460034,33.884201,5.479083,6.043461,13.716349,0.0,21.590839,3.895145,7.469147,-2.708854,1.186801,4.263660
3.0,139.826788,60.304420,52.757590,39.649433,28.314057,-17.488210,-47.788029,20.810153,12.011517,32.718697,5.384658,5.905059,13.368510,0.0,20.810153,3.908505,7.338019,-2.725857,1.137603,4.234677
4.0,139.100519,60.247397,51.833973,39.910201,28.494457,-16.248600,-48.118783,21.116781,12.188089,32.503287,5.704467,5.799424,12.979442,0.0,21.116781,3.829941,6.751558,-3.095246,1.050037,4.321653
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8755.0,157.885706,67.680585,60.048989,44.215478,31.395048,-20.677064,-53.883216,22.725889,13.102554,36.022480,6.153913,6.384372,14.805965,0.0,22.725889,4.077600,7.833184,-3.376490,1.436008,4.869025
8756.0,149.719684,64.347346,56.434623,42.159209,30.004597,-18.892209,-51.156488,21.931907,12.650179,34.566762,5.864202,6.202398,13.904751,0.0,21.931907,3.780188,7.156524,-3.080691,1.154172,4.418091
8757.0,151.325583,64.978874,56.942190,42.453683,30.232750,-19.158434,-51.431255,21.920686,12.645646,34.623076,5.906521,6.185000,14.107272,0.0,21.920686,4.143346,7.714750,-2.988420,1.260348,4.645099
8758.0,145.964644,62.869674,55.512168,41.165542,29.430704,-18.902693,-49.437981,21.788787,12.570787,34.124110,5.675017,5.870994,13.477864,0.0,21.788787,3.756423,7.064135,-2.972419,1.264165,4.337766
8759.0,142.311891,61.188464,53.430094,39.972388,28.578764,-17.875364,-48.029341,21.120655,12.188663,33.203374,5.448917,5.864436,13.632941,0.0,21.120655,4.018427,7.317077,-2.832832,1.322127,4.199119